name: Dune Format

on: 
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ocaml and Dune
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"

      - name: Install dependencies
        run: opam exec -- dune build @install

      - name: Format code
        run: opam exec -- dune build @fmt --auto-promote
