name: Dune Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OPAM
        run: |
          sudo apt install opam
          
      - name: Install OCaml
        run: |
          opam init --bare -a -y
          opam update
          opam switch create gitaction ocaml-base-compiler.5.1.1
          eval $(opam env)

      - name: Install Dune
        run: |
          opam install -y qcheck ocamlformat --switch=gitaction
          eval $(opam env)

      - name: Run Dune Format
        run: dune fmt --auto-promote