name: Format code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install opam
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ca-certificates
          wget https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
          sh install.sh -y
          eval $(opam config env)

      - name: Install OCaml
        run: opam switch create 4.13.1

      - name: Install Dune
        run: opam install dune

      - name: Format code
        run: dune build @fmt --auto-promote