name: Dune Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OPAM
        run: |
          sudo apt install opam
          
      - name: Install OCaml
        run: |
          opam init --bare -a -y
          opam update
          opam switch create gitaction ocaml-base-compiler.5.1.1
          eval $(opam env --switch=gitaction --set-root)
          

      - name: Install Dune
        run: |
          opam install -y ocamlformat 
          eval $(opam env)
          

      - name: Run Dune Format
        run: |
          /home/runner/.opam/gitaction/bin/dune fmt 