name: Format OCaml Code

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest  # Adjust OS as needed
    steps:
      - uses: actions/checkout@v3

      - name: Install opam
        uses: ocaml/opam@v2  # Replace v2 with desired opam version

      - name: Install ocamlformat
        run: opam install ocamlformat

      - name: Set environment variables (optional)
        # Uncomment if opam env vars are not set automatically
        run: |
          echo 'export OPAMROOT=$HOME/.opam' >> $GITHUB_ENV  # Adjust path if needed
          echo 'export PATH=$OPAMROOT/bin:$PATH' >> $GITHUB_ENV

      - name: Format code
        run: dune fmt
