name: Dune Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OPAM
        run: |
          sudo add-apt-repository ppa:avsm/ppa -y
          sudo apt-get update -y
          sudo apt-get install opam -y

      - name: Install OCaml
        run: |
          opam init -y
          opam switch create 5.1 --repos=default --freetype
          eval $(opam env)

      - name: Install Dune
        run: opam install dune --switch=default

      - name: Run Dune Format
        run: dune fmt --auto-promote