name: Dune Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OPAM
        run: |
          sudo apt install opam
          

      - name: Install OCaml
        run: |
          opam init --bare -a -y
          opam switch create 5.1 --repos=default --freetype
          eval $(opam env)

      - name: Install Dune
        run: opam install -y odoc ounit2 qcheck bisect_ppx menhir ocaml-lsp-server ocamlformat --switch=default

      - name: Run Dune Format
        run: dune fmt --auto-promote