name: Format OCaml Code

on:
  push:
    branches: [ main ]

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dune
        uses: nmittu/setup-dune@v2
        with:
          packages: "ocamlformat"
          compiler: "4.12.0"
      - name: build
        run: |
          eval $(opam config env)
          dune fmt